name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  linux_build_and_release:
    name: Build on GNU/Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Create the artifact
      run: |
        nix-env -i cachix -f '<nixpkgs>'
        cachix use ghc9-native-bignum
        nix-build build/artifact.nix
        mv result/janitor.tar.gz ./janitor-${{ runner.os }}.tar.gz

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: true
        prerelease: true
        files: |
          janitor-${{ runner.os }}.tar.gz
