name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  linux_build_and_release:
    name: Build on GNU/Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: cachix/install-nix-action@v13
      with:
        skip_adding_nixpkgs_channel: true

    - name: Create the artifact
      run: |
        nix-env -iA nixpkgs.cachix nixpkgs.upx nixpkgs.tar
        cachix use ghc9-native-bignum
        nix-build build/artifact.nix
        mv result/janitor.tar.gz ./janitor-${{ runner.os }}.tar.gz
      env:
        NIX_PATH: nixpkgs=https://github.com/nixos/nixpkgs-channels/tarball/6613a30c5e3ee59753181512b4bedd4121569925

    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        draft: true
        prerelease: true
        files: |
          janitor-${{ runner.os }}.tar.gz
